[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Aleksey Rostovskiy <aleksey.rostovskiy@jetbrains.com>"]
edition = "2018"

[dependencies]

[profile.release]
lto = "fat"
codegen-units = 1

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"